# app-deployer app config file
---
# App inventory
app-inventory:
  # Type of inventory - supported types: file, mysql
  type: file
  # Inventory file - only required for type == file
  file:
# Ansible settings
ansible:
  # Path containing Ansible executables
  path:
# Host settings
hosts:
  # Root directory to install apps into
  app-root: $HOME/apps
...
